version: "3"
services:

  redis:
    image: redis:alpine

  db:
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:alpine

  django-migrations:
    image: eggmancw/plant_grower:latest
    command: /bin/sh -c python manage.py makemigrations plantgrower && python manage.py migrate

  plantgrower:
    image: eggmancw/plant_grower:latest

  celery-worker:
    image: eggmancw/plant_grower:latest
    command: celery -A plant_grower worker -l info

  celery-beat:
    image: eggmancw/plant_grower:latest
    command: celery -A plant_grower beat -l info

networks:

volumes: