# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plantgrower', '0003_auto_20171124_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grow',
            old_name='last_light_switch',
            new_name='light_switch_date',
        ),
        migrations.AddField(
            model_name='grow',
            name='stage_switch_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
